services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      CORS_ORIGIN: ${CORS_ORIGIN}
      REDIS_HOST: shared_redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    networks:
      - infrastructure_network

networks:
  infrastructure_network:
    external: true